### PR TITLE
Adds pre-configured css that is supposedly suppose to be able to work…

### PR DESCRIPTION
**Pull request by abiodun0**
This PR fixes an error where css is not being easily compiled on the server and rendered on the component. It allows for server-side css rendering with import 'path-to-css-file-name'.

#35

### CODE REVIEW

**Comment by abiodun0** [comment]
Errrm @andela-rsadiq @andela-kerinoso  @andela-uawili Pls who is going to Review/approve/merge this wonderful PR cc @andela-kanyanwu

**Comment by abiodun0** [comment]
This PR fixes a error. where css are not being easily compiled on the server and rendered on teh component. It allows for server side css rendering with `import 'path-to-css-file-name'`.

**Comment by andela-rsadiq** [comment]
This looks good to me. Is there a way we could test that it works fine befoe we merge it in, @abiodun0 ?

**Review by ruqoyyasadiq — APPROVED** [review]
tested and confirm to be the right fix...PR approved!

**Comment by andela-kanyanwu** [comment]
@andela-kadeniyi please can you help with review?

**Review by kayodeadeniyi — APPROVED** [review]
GTM

**Pull request merged**
